name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements_ci.txt') }}

      - name: Install dependencies
        run: pip install -r requirements_ci.txt

      - name: Run flake8
        run: flake8 --verbose

      - name: Run black
        run: black . --check